// js/config.js
// ข้อมูลคงที่: ข้อความภาษา (i18n) และการตั้งค่าด่าน

export const TRANSLATIONS = {
    th: {
        title: "Equation Rush",
        subtitle: "180 IQ",
        mode_title: "โหมดการเล่น",
        custom_mode: "⚙️ Sandbox Mode",
        setup_title: "ตั้งค่าเกม",
        select_target: "เป้าหมาย (Target)",
        select_numbers: "จำนวนตัวเลข",
        select_time: "เวลาจำกัด",
        start_game: "เริ่มเกม",
        solo_mode: "👤 เล่นคนเดียว (Solo)",
        multi_mode: "👥 เล่นหลายคน (Coming Soon)",
        solo_info: 'เลือก "เล่นคนเดียว" เพื่อเข้าสู่โหมดด่าน',
        level_prefix: "ด่าน:",
        score_prefix: "คะแนน:",
        target: "🎯 เป้าหมาย",
        numbers: "🔢 ตัวเลข",
        numbers_unit: "ตัว",
        time_limit: "⏳ เวลา",
        start_level: "เริ่มด่านนี้!",
        back_menu: "ย้อนกลับเมนูหลัก",
        target_prefix: "เป้าหมาย:",
        placeholder: "สมการของคุณ เช่น (5*10) + 8",
        submit: "ส่งคำตอบ",
        shuffle: "สุ่มเลขใหม่",
        shuffle_limit: (count) => `สิทธิ์สุ่มใหม่: ${count} 🎫`,
        shuffle_exhausted: "สิทธิ์หมด! 🍀",
        next_level: "▶️ ไปด่านถัดไป",
        success: "สมการถูกต้องและใช้ตัวเลขได้ครบ",
        error_format: "Syntax Error: รูปแบบสมการไม่ถูกต้อง",
        error_result_nan: `Incorrect Result: สมการได้ผลลัพธ์ที่ไม่ถูกต้อง (NaN/Infinity).`,
        error_result_mismatch: (calc, target) => `Incorrect Result: สมการได้ ${calc} แต่ควรเป็น ${target}.`,
        error_usage: "Number Usage Error: คุณใช้ตัวเลขไม่ได้รับอนุญาตหรือใช้ซ้ำมากเกินไป",
        time_up: "หมดเวลา! ลองใหม่นะ.",
        final_win: "คุณเก่งมาก! ผ่านครบทุกด่านแล้ว!",
        time_unit_min: (n) => `${n} นาที`,
        time_unit_sec: (n) => `${n} วินาที`,
        power: "^",
        factorial: "!",
        level_1_desc: "เริ่มต้น: เป้าหมาย 2 หลัก, ใช้เลข 5 ตัว, 3 นาที",
        level_2_desc: "ลดเวลา: เป้าหมาย 2 หลัก, ใช้เลข 5 ตัว, 2:45 นาที",
        level_3_desc: "ลดตัวเลข: เป้าหมาย 2 หลัก, ใช้เลข 4 ตัว, 2 นาที",
        level_4_desc: "กดดันเวลา: เป้าหมาย 2 หลัก, ใช้เลข 4 ตัว, 1:30 นาที",
        level_5_desc: "เพิ่มความยาก: เป้าหมาย 3 หลัก (100-499), 5 ตัวเลข, 3 นาที",
        level_6_desc: "กดดัน: เป้าหมาย 3 หลัก (100-499), 5 ตัวเลข, 2:45 นาที",
        level_7_desc: "ยากขึ้น: เป้าหมาย 3 หลัก (100-499), 5 ตัวเลข, 2 นาที",
        level_8_desc: "ยากที่สุด: เป้าหมาย 3 หลัก (500-999), 5 ตัวเลข, 1:30 นาที",
        level_9_desc: "ทดสอบสุดท้าย: เป้าหมาย 3 หลัก (500-999), 5 ตัวเลข, 1:30 นาที",
        level_10_desc: "THE FINAL CHALLENGE: เป้าหมาย 3 หลัก (500-999), 5 ตัวเลข, 1:30 นาที",
    },
    en: {
        title: "Equation Rush",
        subtitle: "180 IQ",
        mode_title: "Game Modes",
        solo_mode: "👤 Solo Play",
        custom_mode: "⚙️ Sandbox Mode",
        setup_title: "Game Setup",
        select_target: "Target Type",
        select_numbers: "Number Count",
        select_time: "Time Limit",
        start_game: "Start Game",
        multi_mode: "👥 Multiplayer (Coming Soon)",
        solo_info: 'Select "Solo Play" to enter Level Mode.',
        level_prefix: "Level:",
        score_prefix: "Score:",
        target: "🎯 Target",
        numbers: "🔢 Numbers",
        numbers_unit: "units",
        time_limit: "⏳ Time",
        start_level: "Start Level!",
        back_menu: "Back to Main Menu",
        target_prefix: "TARGET:",
        placeholder: "Your equation, e.g., (5*10) + 8",
        submit: "Submit Answer",
        shuffle: "Shuffle Numbers",
        shuffle_limit: (count) => `Shuffle Tickets: ${count} 🎫`,
        shuffle_exhausted: "Tickets Exhausted! 🍀",
        next_level: "▶️ Next Level",
        success: "Equation is correct and numbers are used properly.",
        error_format: "Syntax Error: Invalid Equation Format.",
        error_result_nan: `Incorrect Result: Equation leads to an invalid number (NaN/Infinity).`,
        error_result_mismatch: (calc, target) => `Incorrect Result: Equation equals ${calc}, but should be ${target}.`,
        error_usage: "Number Usage Error: You used an unauthorized number or used one too many times.",
        time_up: "TIME UP! Try again.",
        final_win: "Congratulations! You completed all levels!",
        time_unit_min: (n) => `${n} min`,
        time_unit_sec: (n) => `${n} sec`,
        power: "^",
        factorial: "!",
        level_1_desc: "Easy Start: 2-digit target, 5 numbers, 3 minutes.",
        level_2_desc: "Time Reduction: 2-digit target, 5 numbers, 2:45 minutes.",
        level_3_desc: "Fewer Numbers: 2-digit target, 4 numbers, 2 minutes.",
        level_4_desc: "Time Pressure: 2-digit target, 4 numbers, 1:30 minutes.",
        level_5_desc: "Difficulty Up: 3-digit target (100-499), 5 numbers, 3 minutes.",
        level_6_desc: "Pressure: 3-digit target (100-499), 5 numbers, 2:45 minutes.",
        level_7_desc: "Harder: 3-digit target (100-499), 5 numbers, 2 minutes.",
        level_8_desc: "Hardest: 3-digit target (500-999), 5 numbers, 1:30 minutes.",
        level_9_desc: "Final Test: 3-digit target (500-999), 5 numbers, 1:30 minutes.",
        level_10_desc: "THE FINAL CHALLENGE: 3-digit target (500-999), 5 numbers, 1:30 minutes.",
    }
};

export const LEVELS = [
    { id: 1,  targetDigits: 2, numberCount: 5, timeLimitSeconds: 180, targetRange: { min: 10,  max: 99  } },
    { id: 2,  targetDigits: 2, numberCount: 5, timeLimitSeconds: 165, targetRange: { min: 10,  max: 99  } },
    { id: 3,  targetDigits: 2, numberCount: 4, timeLimitSeconds: 120, targetRange: { min: 10,  max: 99  } },
    { id: 4,  targetDigits: 2, numberCount: 4, timeLimitSeconds: 90,  targetRange: { min: 10,  max: 99  } },
    { id: 5,  targetDigits: 3, numberCount: 5, timeLimitSeconds: 180, targetRange: { min: 100, max: 499 } },
    { id: 6,  targetDigits: 3, numberCount: 5, timeLimitSeconds: 165, targetRange: { min: 100, max: 499 } },
    { id: 7,  targetDigits: 3, numberCount: 5, timeLimitSeconds: 120, targetRange: { min: 100, max: 499 } },
    { id: 8,  targetDigits: 3, numberCount: 5, timeLimitSeconds: 90,  targetRange: { min: 500, max: 999 } },
    { id: 9,  targetDigits: 3, numberCount: 5, timeLimitSeconds: 90,  targetRange: { min: 500, max: 999 } },
    { id: 10, targetDigits: 3, numberCount: 5, timeLimitSeconds: 90,  targetRange: { min: 500, max: 999 } },
];
